camera_frame: pylon_camera
device_user_id: ""
camera_info_url: "file:///home/xavier/git/NIA_AI_DATABASE/ros/src/app/logging_box/config/camera.yaml"
image_encoding: "bayer_bggr8"
frame_rate: 15
brightness: 20
brightness_continuous: true
exposure_auto: true
gain_auto: true